import os
print('')
print('*************************************************')
print('Linux en Android por Nicolas para el mundo -2018-')
print('********************Python-3*********************')
print('')
print ("Saludos,para instalar y ejecutar LXDE Sigue estos pasos C:")
print('')
print('Que deseas hacer??')
print('')
print('*************************')
print('-A = Instalar Componentes')
print('-B = Instalar LXDE')
print('-C = Ejecutar LXDE')
print('-D = Actualizar Debian')
print('-E = Instrucciones')
print('-F = Instalar LXDE-Core')
print('-G = Reparar permisos')
print('*************************')
print('')
a=input("Selecciona una opcion: ")
if a=="A":
 os.system('apt-get install xterm pulseaudio synaptic')
 print('Listo!!')
if a=="B":
 os.system('apt-get install lxde')
 print('Listo, ya puedes ejecutar LXDE En XSERVER')
if a=="C":
 os.system('./iniciar.sh')
 print('Listo!!')
 print('Recuerda iniciar Xserver XDSL antes del Scritp!')
if a=="D":
 os.system('apt-get update && apt-get upgrade')
 print('Listo!!')
if a=="E":
 print('Saludos,es necesario tener instaladas las aplicaciones GNURoot Debian')
 print('y Xserver XSDL, ejecutar este script desde GNURoot Debian')
 print('Actualizar Debian,instalar los componentes luego instalar LXDE')
 print('iniciar la aplicacion Xserver, luego ejecutar LXDE.')
 print('PD: Recuerda Reparar los permisos!!')
 print('LXDE-Core es una version mas liviana con solo lo basico y necesario en LXDE')
 print('')
 print('y esta todo LISTO!!!')
if a=="F":
	print('LXDE-Core es una version mas liviana que solo cuenta con')
	print('el entorno de escritorio LXDE')
	os.system('apt-get install lxde-core')
	print('Listo ya puedes ejecutar LXDE en XSERVER')
if a=="G":
 os.system('chmod +x iniciar.sh')
 print('Listo!')
    		 
print('*************')
print('*KXLYB3RTI0N*')
print('*************')
